// TODO: Update `add_ticket`'s signature: it should take a `TicketDraft` as input
//  and return a `TicketId` as output.
//  Each ticket should have a unique id, generated by `TicketStore`.
//  Feel free to modify `TicketStore` fields, if needed.
//
// You also need to add a `get` method that takes as input a `TicketId`
// and returns an `Option<&Ticket>`.

use crate::exercises::tv2_description::TicketDescription;
use crate::exercises::tv2_title::TicketTitle;

#[derive(Clone)]
pub struct TicketStore {
    tickets: Vec<Ticket>,
    next_id: u64,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TicketId(u64);

#[derive(Clone, Debug, PartialEq)]
pub struct Ticket {
    pub id: TicketId,
    pub title: TicketTitle,
    pub description: TicketDescription,
    pub status: Status,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TicketDraft {
    pub title: TicketTitle,
    pub description: TicketDescription,
}

#[derive(Clone, Debug, Copy, PartialEq)]
pub enum Status {
    ToDo,
    InProgress,
    Done,
}

impl TicketStore {
    pub fn new() -> Self {
        Self {
            tickets: Vec::new(),
            next_id: 0,
        }
    }
    
    pub fn add_ticket(&mut self, draft: TicketDraft) -> TicketId {
		let TicketDraft { description, title } = draft;
		self.next_id += 1;
		
		let id = TicketId(self.next_id);
		self.tickets.push(Ticket {
			title,
			description,
			id,
			
			status: Status::ToDo,
		});
		
		id
	}

	pub fn get(&self, id: TicketId) -> Option<&Ticket> {
		self.tickets.iter()
			.find(|ticket| ticket.id == id )
	}
}

fn ticket_title() -> TicketTitle {
    TicketTitle::try_from("This is a title").unwrap()
}

fn ticket_description() -> TicketDescription {
    TicketDescription::try_from(
        "ths is a description and it is quite lng and it really
        is you cna just read this really if you want proof",
    )
    .unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn works() {
        let mut store = TicketStore::new();

        let draft1 = TicketDraft {
            title: ticket_title(),
            description: ticket_description(),
        };
        let id1 = store.add_ticket(draft1.clone());
        let ticket1 = store.get(id1).unwrap();
        assert_eq!(draft1.title, ticket1.title);
        assert_eq!(draft1.description, ticket1.description);
        assert_eq!(ticket1.status, Status::ToDo);

        let draft2 = TicketDraft {
            title: ticket_title(),
            description: ticket_description(),
        };
        let id2 = store.add_ticket(draft2);

        assert_ne!(id1, id2);
    }
}
